import { Geist, Geist_Mono } from "next/font/google";  // Import fonts from Google
import "./globals.css";  // Global styles
import { CartProvider } from "@/context/CartContext";  // Cart context provider

// Import fonts and assign variables to use them globally
const geistSans = Geist({
  variable: "--font-geist-sans", // Define a variable for the Geist font
  subsets: ["latin"], // Define the subsets you want (latin in this case)
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // Define a variable for the Geist Mono font
  subsets: ["latin"], // Define the subsets you want (latin in this case)
});

// Metadata for the document
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root Layout Component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Optional: If you want to include other meta tags, styles, or icons */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}  // Apply font variables to the body
      >
        <CartProvider>
          {children} 
        </CartProvider>
      </body>
    </html>
  );
}
